app/models/post.py
from app import db, login
from datetime import datetime
from app.models import User


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Post(db.Model):
    __tablename__ = 'posts'
    __searchable__ = ['title', 'subtitle', 'content']
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    subtitle = db.Column(db.String)
    content = db.Column(db.Text)
    date = db.Column(db.String, default=datetime.now().strftime('%B %d %Y'))
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref='post', lazy='dynamic')
    tags = db.relationship('Tag', backref='post', lazy='dynamic')
    post_image_url= db.Column(db.String)

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)

    def __repr__(self):
        return '<Post %r>' % self.title

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, TextAreaField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo
from flask import request

class CommentForm(FlaskForm):
    content = TextAreaField('Enter your comment', validators=[DataRequired()])
    submit = SubmitField('Submit')

class TagForm(FlaskForm):
    tag = StringField('Enter tag', validators=[DataRequired()])

class ProfileForm(FlaskForm):
    username = StringField(validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Update My Profile')


class ContactForm(FlaskForm):
    username = StringField(validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    message = TextAreaField('Enter your message', validators=[DataRequired()])
    submit = SubmitField('Send a message')

app/main/__init__.py
from app.main.errors import * 
from app.main.views import main

app/main/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, current_app, g, session
from flask_login import current_user
from app import decorators
from app.models import User, Post, Comment, Tag
from slugify import slugify
from app.main.forms import CommentForm, TagForm, ProfileForm, ContactForm
from app import db
from flask_mail import Message
from app import mail


main = Blueprint('main', __name__)

def manage_prev_page():
    global session, request
    if 'profile' not in request.referrer and 'change_password' not in request.referrer \
    and 'forgot_password' not in request.referrer \
    and 'request_password'  not in request.referrer:
        session['prev_page'] = request.referrer

@main.route('/')
def homepage():
    return render_template('main/homepage.html')

@main.route('/about', methods=['GET', 'POST'])
def about():
    return render_template('main/about.html')


@main.route('/blog')
def blog():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.paginate(page=page, per_page=5)
    tags = Tag.query.all()
    return render_template('main/blog.html', posts=posts, slugify=slugify, tags=tags)


@main.route('/blog/post/<int:post_id>/<string:post_url>', methods=['GET', 'POST'])
def post(post_id, post_url):
    post = Post.query.filter_by(id=post_id).first()
    tags = Tag.query.filter_by(id=post_id)
    form = CommentForm()
    comments = Comment.query.filter_by(post_id=post_id).order_by(Comment.date.desc())
    tags = Tag.query.filter_by(post_id=post_id)
    if form.validate_on_submit():
        if current_user.is_authenticated:
            comment = Comment(content=form.content.data,
                              post_id=post_id, author_id=current_user.id)
            db.session.add(comment)
            db.session.commit()
            flash('Your comment has been published')
            return redirect(url_for('main.post', post_id=post_id, post_url=post_url))
        else: 
            flash('You need to get logged in to comment')
    return render_template('main/post.html', post=post, form=form, comments=comments, tags=tags, post_id=post_id, post_url=post_url )

@main.route('/profile', methods=['GET', 'POST'])
@decorators.login_required
def profile():
    if request.method == 'GET':
        manage_prev_page()
    form = ProfileForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            current_user.username = form.username.data
            current_user.email = form.email.data
            db.session.commit()
            flash('Your account has been changed!')
            return redirect(session['prev_page'])
        else:
            flash('Please check your data!')
    return render_template('main/profile.html', form=form)



    



        

app/templates/main/about.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Personal website of Gennadii Turutin">
  <meta name="author" content="Gennadii Turutin">
  <title>About</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/square.png') }}">
  <!-- Bootstrap core CSS -->
  <link href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{{url_for('static', filename='css/animate.css')}}">
  <link href="{{url_for('static', filename='css/resume.css')}}" rel="stylesheet" type="text/css">
  <!-- Bootstrap core JavaScript -->
  <script src="static/vendor/jquery/jquery.min.js"></script>
  <script src="static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- jQuery -->
  <script src="static/js/jquery.min.js"></script>
  <!-- jQuery Easing -->
  <script src="static/js/jquery.easing.1.3.js"></script>
  <!-- Bootstrap -->
  <script src="static/js/bootstrap.min.js"></script>
  <!-- Waypoints -->
  <script src="static/js/jquery.waypoints.min.js"></script>
  <!-- Stellar Parallax -->
  <script src="static/js/jquery.stellar.min.js"></script>
  <!-- CountTo  -->
  <script src="static/js/jquery.countTo.js"></script>
  <!-- Main JS (Do not remove) -->
  <script src="static/js/main.js"></script>
</head>

<body id="page-top">
  {% include "partials/navbar.html" %}
  {% block navbar %}
  {% endblock %}

  <!-- Flash messages -->
  {% include "partials/flash.html" %}
  {% block flash %}
  {% endblock %}

  <div class="container-fluid p-3" id="soderzhanie">
    <section class="resume-section p-0 p-lg-5 d-flex align-items-center" id="about">
      <div class="w-100">
        <h2 class="mb-2 to-animate">Gennadii Turutin</h2>
        <a class="navbar-brand">
            <span class="d-lg-block">
              <img class="img-fluid img-profile mx-auto mb-2" src="{{ url_for('static', filename='img/turutin.jpg') }}" alt="" width="280" height="200">
            </span>
        </a>
        
        <div class="subheading mb-2 text-dark">Contact</div>
        <div class="resume-date mb-1 text-md-left">
          <ul class="fa-ul mb-2">
            <li>
            <i class="fa-li fa fa-angle-right"></i>
            <h2 class="lead mb-0">gennadii.turutin@gmail.com</h2>
            </li>
            <li>
              <i class="fa-li fa fa-angle-right"></i>
              <h2 class="lead mb-0">NY, New York</h2>
            </li>
          </ul>
        </div>
        <div class="social-icons">
            <a href="https://www.linkedin.com/in/gennadii-turutin/"  target="_blank">
              <i class="fab fa-linkedin"></i>
            </a>
            <a href="https://github.com/GennadiiTurutin"  target="_blank">
              <i class="fab fa-github-square"></i>
            </a>
          </div>

        <div class="subheading mb-2 text-dark">About me</div>
        <div class="resume-date mb-1 text-md-left">
          <ul class="fa-ul mb-2">
            <li>
            <i class="fa-li fa fa-child"></i>
            <h2 class="lead mb-0">
            I'm a software engineer with the focus on data.<br>
            I leverage Python and JavaScript in combination with cloud services 
            to build reliable and efficient applications that will retrieve, store, 
            and manipulate data. <br>
            My belief is that programming skills are secondary.
            Planning and the ability to break problems up into a set of trivial problems are primary. 
            </h2>
            </li>
          </ul>
        </div>
      </div>
    </section>

    <section class="resume-section p-3 p-lg-5 d-flex align-items-center">
      <div class="w-100">
        <h2 class="mb-1">Experience</h2>

        <div class="subheading mb-2 text-dark">Data Acquisition Developer</div>
        <div class="resume-date mb-1 text-md-left">
          <span class="text-primary">October 2019 - Present (New York, USA)</span>
        </div>
        <div class="resume-date mb-1 text-md-left">
          <ul class="fa-ul mb-2">
            <li>
            <i class="fa-li fa fa-angle-right"></i>
            Prescriptive Data
            </li>
          </ul>
        </div>

        <div class="subheading mb-2 text-dark">Data Engineer</div>
        <div class="resume-date mb-1 text-md-left">
          <span class="text-primary">May 2019 - October 2019 (New York, USA)</span>
        </div>
        <div class="resume-date mb-1 text-md-left">
          <ul class="fa-ul mb-2">
            <li>
            <i class="fa-li fa fa-angle-right"></i>
            ThinkEmpire.io
            </li>
          </ul>
        </div>

        <div class="subheading mb-2 text-dark">Full-Stack Developer</div>
        <div class="resume-date mb-1 text-md-left">
          <span class="text-primary">Jan 2019 - May 2019 (New York, USA)</span>
        </div>
        <div class="resume-date mb-1 text-md-left">
          <ul class="fa-ul mb-2">
            <li>
            <i class="fa-li fa fa-angle-right"></i>
            Freelance
            </li>
          </ul>
        </div>

        <div class="subheading mb-2 text-dark">Architectural Planner</div>
        <div class="resume-date mb-1 text-md-left">
          <span class="text-primary">Sep 2017 - Jan 2019 (New York, USA)</span>
        </div>
        <div class="resume-date mb-1 text-md-left">
          <ul class="fa-ul mb-2">
            <li>
            <i class="fa-li fa fa-angle-right"></i>
            RISE Architecture
            </li>
          </ul>
        </div>

        <div class="subheading mb-2 text-dark">Technical Specialist</div>
        <div class="resume-date mb-1 text-md-left">
          <span class="text-primary">Feb 2013 - Sep 2016 (Moscow, Russia)</span>
        </div>
        <div class="resume-date mb-1 text-md-left">
          <ul class="fa-ul mb-2">
            <li>
            <i class="fa-li fa fa-angle-right"></i>
            Schmitz Cargobull Russland
            </li>
          </ul>
        </div>

        <div class="subheading mb-2 text-dark">Technical intern</div>
        <div class="resume-date mb-1 text-md-left">
          <span class="text-primary">Aug 2011 - Feb 2013 (Moscow, Russia)</span>
        </div>
        <div class="resume-date mb-1 text-md-left">
          <ul class="fa-ul mb-2">
          <li>
          <i class="fa-li fa fa-angle-right"></i>
            Robert Bosch
          </li>
          </ul>
        </div>
    </section>

    <section class="resume-section p-3 p-lg-5 d-flex align-items-center">
      <div class="w-100">
        <h2 class="mb-1">Education</h2>
        <div class="subheading mb-1 text-dark">New York University</div>
        <div class="resume-date mb-1 text-md-left">
          <span class="text-primary">2017 (New York, USA)</span>
        </div>
        <ul class="fa-ul mb-2">
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Advanced Python Programming
          </li>
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Data mining, predictive analytics, and Big Data
          </li>
        </ul>

        <div class="subheading mb-2 text-dark">Higher School of Economics</div>
        <div class="resume-date mb-1 text-md-left">
          <span class="text-primary">2015-2016 (Moscow, Russia)</span>
        </div>
        <ul class="fa-ul mb-2">
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Financial Management
          </li>
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Statistics
          </li>
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Economics
          </li>
        </ul>

        <div class="subheading mb-2 text-dark"> Peoples' Friendship University of Russia</div>
        <div class="resume-date mb-1 text-md-left">
          <span class="text-primary">2008 - 2014 (Moscow, Russia)</span>
        </div>
        <ul class="fa-ul mb-0">
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Bachelor degree in Mechanical Engineering
          </li>
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Courses of German language
          </li>
        </ul>
      </div>
    </section>

    <section class="resume-section p-3 p-lg-5 d-flex align-items-center">
      <div class="w-100">
        <h2 class="mb-3">Skills</h2>

        <div class="subheading mb-3 text-dark">Programming Languages &amp; Tools</div>
        <ul class="list-inline dev-icons">
          <li class="list-inline-item">
            <i class="fab fa-python"></i>
          </li>
          <li class="list-inline-item">
            <i class="fab fa-linux"></i>
          </li>
          <li class="list-inline-item">
            <i class="fab fa-aws"></i>
          </li>
          <li class="list-inline-item">
              <i class="fab fa-google"></i>
            </li>
          <li class="list-inline-item">
            <i class="fab fa-docker"></i>
          </li>
          <li class="list-inline-item">
            <i class="fab fa-jenkins"></i>
          </li>
          <li class="list-inline-item">
            <i class="fab fa-js-square"></i>
          </li>
          <li class="list-inline-item">
            <i class="fab fa-angular"></i>
          </li>
          <li class="list-inline-item">
            <i class="fab fa-react"></i>
          </li>
          <li class="list-inline-item">
            <i class="fab fa-node-js"></i>
          </li>
          <li class="list-inline-item">
            <i class="fab fa-npm"></i>
          </li>
        </ul>

        <div class="subheading mb-3 text-dark">Web Frameworks &amp; Libraries</div>
        <ul class="fa-ul mb-0">
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Django, Flask, pandas, numpy, pandas, etc.
          </li>
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            React, Angular, Express
          </li>
        </ul>

        <div class="subheading mt-3 mb-3 text-dark">Areas of Proficiency</div>
        <ul class="fa-ul mb-0">
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Cross Functional Teams
          </li>
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Agile Development &amp; Scrum
          </li>
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Data Engineering &amp; Data Acquisition
          </li>
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Data Analysis &amp; ETL
          </li>
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Data Visualization
          </li>
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Machine Learning
          </li> 
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Full-Stack
          </li>
          <li>
            <i class="fa-li fa fa-angle-right"></i>
            Continious Integration &amp; Development
          </li>
        </ul>
      </div>
    </section>
  </div>
</body>
</html>

app/templates/main/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Personal website of Gennadii Turutin">
  <meta name="author" content="Gennadii Turutin">
  <title>Blog</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/square.png') }}">
  <!-- Bootstrap core CSS -->
  <link href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template -->
  <link href="{{url_for('static', filename='css/resume.css')}}" rel="stylesheet" type="text/css">
  <!-- Bootstrap core JavaScript -->
  <script src="static/vendor/jquery/jquery.min.js"></script>
  <script src="static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- Plugin JavaScript -->
  <script src="static/vendor/jquery-easing/jquery.easing.min.js"></script>
  <!-- Custom scripts for this template -->
  <script src="static/js/resume.min.js"></script>
</head>

<body id="page-top">
  <!-- Navigation -->
  {% include "partials/navbar.html" %}
  {% block navbar %}
  {% endblock %}

  <!-- Flash messages -->
  {% include "partials/flash.html" %}
  {% block flash %}
  {% endblock %}

  <div class="container-fluid p-3" id="soderzhanie">
    <section class="resume-section p-0 p-lg-5 d-flex align-items-center" id="blog">
      <div class="w-100">
        <h2 class="mb-2">Posts</h2>
              {% for post in posts.items %}
                <div class="subheading mt-5 mb-2 p-2 text-dark" id="post">
                  <a href="{{ url_for('main.post', post_id = post.id, post_url=slugify(post.title)) }}">
                    <h3 class="text-left mb-2">{{ post.title }}</h3>
                    <h4 class="text-left mb-2">{{ post.subtitle }}</h4>
                    <h6 class="lead text-left mb-4">Posted by {{ post.user.username }} on {{ post.date }}</h6>
                  </a>  
                </div>
              {% endfor %}

              {% for page_num in posts.iter_pages() %}
                {% if page_num %}
                  <a class="btn btn-outline-secondary mb-4" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
                  {% else %}
                  ...
                {% endif %}
              {% endfor %}
      </div>
    </section>
  </div>
</body>
</html>

app/templates/main/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Personal website of Gennadii Turutin">
  <meta name="author" content="Gennadii Turutin">
  <title>Gennadii Turutin</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/square.png') }}">
  <!-- Bootstrap core CSS -->
  <link href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{{url_for('static', filename='css/animate.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Saira+Semi+Condensed:600&display=swap" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
  <!-- jQuery -->
  <script src="static/js/jquery.min.js"></script>
  <!-- jQuery Easing -->
  <script src="static/js/jquery.easing.1.3.js"></script>
  <!-- Bootstrap -->
  <script src="static/js/bootstrap.min.js"></script>
  <!-- Waypoints -->
  <script src="static/js/jquery.waypoints.min.js"></script>
  <!-- Stellar Parallax -->
  <script src="static/js/jquery.stellar.min.js"></script>
  <!-- CountTo  -->
  <script src="static/js/jquery.countTo.js"></script>
  <!-- Main JS (Do not remove) -->
  <script src="static/js/main.js"></script>
</head>
<body>
  <section id="fh5co-home" data-section="home" style="background-color: black">
    <div class="container">
      <div class="text-wrap">
        <div class="text-inner">
          <div class="row">
            <div class="col-12 text-center mt-4 mb-4">
              <div id="socicons mb-4">
                <ul class="list-inline mb-2 mt-0">
                  <li class="list-inline-item">
                    <a class="btn btn-outline-light btn-social text-center text-grey" href="https://www.linkedin.com/in/gennadii-turutin/">
                      <i class="fab fa-fw fa-linkedin-in"></i>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a class="btn btn-outline-light btn-social text-center text-grey" href="https://github.com/GennadiiTurutin">
                        <i class="fab fa-fw fa-github"></i>
                    </a>
                  </li>
                </ul> 
              </div>
            </div>
            <div class="col-12 text-center mt-4 mb-4">
              <h1 class="text-white" style="font-family: 'Saira Semi Condensed', sans-serif;" id="name">Gennadii Turutin</h1>
              <h2 class="to-animate" style="font-family: 'Saira Semi Condensed', sans-serif;" id="title">Software Engineer</h2>
              <ul class="list-inline mb-2 mt-0">
                  <li class="list-inline-item">
                    <h5 class="to-animate" style="font-family: 'Saira Semi Condensed', sans-serif;"><a class="btn btn-outline-light btn-social text-center text-grey" href="/about">About me</a></h5>
                  </li>
                  <li class="list-inline-item">
                    <h5 class="to-animate" style="font-family: 'Saira Semi Condensed', sans-serif;"><a class="btn btn-outline-light btn-social text-center text-grey" href="/blog">Blog</a></h5>
                  </li>
                </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  </body>
</html>

app/templates/main/post.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Personal website of Gennadii Turutin">
  <meta name="author" content="Gennadii Turutin">
  <title>{{ post.title }}</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/square.png') }}">
  <!-- Bootstrap core CSS -->
  <link href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template -->
  <link href="{{url_for('static', filename='css/resume.css')}}" rel="stylesheet" type="text/css">
  <!-- Bootstrap core JavaScript -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- Plugin JavaScript -->
  <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>
  <!-- Custom scripts for this template -->
  <script src="/static/js/resume.min.js"></script>
</head>

<body id="page-top">
  <!-- Navigation -->
  {% include "partials/navbar.html" %}
  {% block navbar %}
  {% endblock %}

  <!-- Flash messages --> 
  {% include "partials/flash.html" %}
  {% block flash %}
  {% endblock %}

  <div class="container-fluid p-3">
    <section class="resume-section p-0 p-lg-5 d-flex align-items-center" id="text">
      <div class="w-100">
        <h2 class="mb-5">
          {{ post.title }}
        </h2>
        <h3 class="text-left text-dark mt-5 mb-5">
          {{ post.subtitle }}
        </h3>
        <h3 class="lead text-grey">Posted by {{ post.user.username }} on {{ post.date }} </h3>
        <!-- Tags -->
       {% include "partials/tag.html" %}
       {% block tag %}
       {% endblock %}
      </div>
    </section>

    <!-- Post Content -->
    <section class="resume-section p-0 p-lg-5 d-flex align-items-center" id="text">
      <div class="w-100">
        <div class="post-body">
          <p class="lead text-dark"> 
          {{ post.content|safe }}
          </p>
        </div>
      </div>
    </section>

    <!-- Comments -->
    <section class="resume-section p-0 p-lg-5 d-flex align-items-center" id="text">
      <div class="w-100">
        {% include "partials/comment.html" %}
        {% block comment %}
        {% endblock %}
      </div>
    </section>
  </div>
</body>
</html>

app/templates/main/profile.html
<style>
  .cool {
    font-family: 'Saira Semi Condensed', sans-serif; 
  }
</style>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Personal website of Gennadii Turutin">
  <meta name="author" content="Gennadii Turutin">
  <title>Profile</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/square.png') }}">
  <!-- Bootstrap core CSS -->
  <link href="{{url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Saira+Semi+Condensed:600&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
  <link href="{{url_for('static', filename='vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template -->
  <link href="{{url_for('static', filename='signin.css')}}" rel="stylesheet" type="text/css">
  <!-- Bootstrap core JavaScript -->
  <script src="static/vendor/jquery/jquery.min.js"></script>
  <script src="static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- Plugin JavaScript -->
  <script src="static/vendor/jquery-easing/jquery.easing.min.js"></script>
  <!-- Custom scripts for this template -->
  <script src="static/js/resume.min.js"></script>
</head>

{% include "partials/flash.html" %}
{% block flash %}
{% endblock %}

<body class="text-center" style="background-color: white;">
  <div class="content-section" >
    <div id="parent_container">
      <form method="POST" action="{{ url_for('main.profile') }}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4 cool">Profile</legend>
          <img src="{{ current_user.gravatar() }}">
          <div class="form-group">
            {{ form.username.label(class="form-control-label cool") }}
            {{ form.username(class="form-control form-control-md cool", value=current_user.username) }}
          </div>
          <div class="form-group">
            {{ form.email.label(class="form-control-label cool") }}
            {{ form.email(class="form-control form-control-md cool", value=current_user.email) }}
          </div>
        </fieldset>
        <div class="form-group cool">
          {{ form.submit(class="btn btn-outline-secondary btn-md cool") }}
        </div>
      </form>
      <div class="form-group">
        <a class="btn btn-outline-secondary btn-md cool" href="{{ url_for('auth.change_password') }}">Change password</a>
      </div>
      <div class="border-top pt-3">
        <small class="text-muted cool">
          <a class="ml-2" href="{{ url_for('auth.logout') }}">Logout</a>
        </small>
        <small class="text-muted cool">
          <a class="ml-2" href="{{ url_for('auth.back') }}">Back</a>
        </small>
      </div>
    </div>
  </div>
</body>
</html>